services:
    build-agent:
        build:
            context: ./build/
            dockerfile: Dockerfile
        image: kaseed/devops-app:latest
    test-agent:
        build:
            context: ./test/
            dockerfile: Dockerfile
        depends_on:
            - build-agent