pipeline {
    agent any

    stages {
        stage('Build') {
                steps {                    
                    dir('./Pipeline') {
                        sh 'docker-compose build build-agent'
                    }
                }
        }
        stage('Test') {
            steps {
                dir('./Pipeline') {
                    sh 'docker-compose build test-agent'
                    sh 'docker-compose up'
                }
            }
        }
    }
}